Clownless Skates
cosmatic-drift-14/cosmatic-drift pull request #110
Opened 2024-01-08 12:22 UTC by KittenColony

## About the PR
A pair of skates that are monochromatic, can only be found in maints lockers

## Why / Balance
Style choice since not everyone wants clown skates

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
add: Added gray skates, you soulless corpo.
tweak: Added Honk! to skate description

2024-01-08 12:31 UTC, KittenColony commented
Green I need your fucking meta file, where did you PUT IT

2024-01-12 03:02 UTC, Skarletto commented on Resources/Textures/_CD/Clothing/Shoes/Specific/grayskates.rsi/meta.json
> +      "name": "icon"
Make sure your file names are properly renamed as per the meta, so 'Icon' should be 'icon'

2024-01-12 16:03 UTC, LankLTE requested changes
Small nitpick, rest looks good.

2024-01-12 16:03 UTC, LankLTE commented on Resources/Textures/_CD/Clothing/Shoes/Specific/grayskates.rsi/meta.json
> +  "copyright": "Made by brainfood1183 (github), altered by discord: mrgreen06 (358779039810322433)",
Add a link to a commit with the sprite (as it's currently used, just the current commit should be fine).

2024-01-23 05:56 UTC, LankLTE approved these changes

2024-01-23 05:57 UTC, merged