Stylized Maid Dress
cosmatic-drift-14/cosmatic-drift pull request #116
Opened 2024-01-12 04:35 UTC by KittenColony

## About the PR
Due to an incident regarding a wealthy executive and his servants, Nanotrasen has received an influx of highly stylized maid uniforms, accounting is still baffled by the decision to purchase the surplus.

## Why / Balance
Something fun to wear, the apron is objectively worse to wear in most situations

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
add: Added a stylized maid outfit, including advanced heels and a utilitarian apron.

2024-01-12 16:02 UTC, LankLTE submitted a review, later dismissed
Please try to attach in-game (or attached to a sprite) pictures of these.

2024-01-12 19:48 UTC, Nairodian requested changes

2024-01-12 19:53 UTC, LankLTE commented on Resources/Prototypes/_CD/Entities/Clothing/Shoes/boots.yml
> +        Piercing: 6
Disagree on the shoes specifically since heels being a weapon is (kinda) a legit thing and also sort of funny.

2024-01-12 19:57 UTC, Nairodian commented on Resources/Prototypes/_CD/Entities/Clothing/Shoes/boots.yml
> +        Piercing: 6
There's only one shoe item Upstream that has damage, high heeled boots, but they're unobtainable. A PR to add damage to the other types of shoes was denied. I'm willing to back down there, but same concerns as Upstream had for me.

2024-01-13 03:24 UTC, KittenColony commented on Resources/Prototypes/_CD/Entities/Clothing/Belt/belts.yml
> +        - Handcuff
The idea is that its a less specialized belt that can hold less then the more specialized variants

2024-01-13 03:26 UTC, KittenColony commented on Resources/Prototypes/_CD/Entities/Clothing/Shoes/boots.yml
> +        Piercing: 6
It's a single point more then using your hands, but the knife thing is understandable

2024-01-13 03:45 UTC, KittenColony commented
:catjam:

2024-01-13 13:45 UTC, Nairodian approved these changes

2024-01-13 17:25 UTC, merged