Garment packs
cosmatic-drift-14/cosmatic-drift pull request #117
Opened 2024-01-12 09:57 UTC by KittenColony

## About the PR
New tech has allowed nanotrasen to vacuum seal clothes into easy to transport bags, just pull at the seams and watch as your uniform explodes out befo-_AUGH MY NOSE_

## Why / Balance
It allows for outfits to be compressed down into a single item for admins, as well as having the option for "random" to be delivered in places, giving a centralized place to get a full outfit and more

## Technical details

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
add: New garment packs, vacuum sealed kits that when opened, rapidly expand to release the contained garments

2024-01-12 16:09 UTC, LankLTE requested changes

2024-01-12 16:09 UTC, LankLTE commented on Resources/Prototypes/Entities/Clothing/GarmentPacks/clothespack.yml
> +    sprite: _CD/Clothing/GarmenPacks/debugpack.rsi
Should be GarmentPacks not GarmenPacks

2024-01-13 00:19 UTC, KittenColony commented on Resources/Prototypes/Entities/Clothing/GarmentPacks/clothespack.yml
> +    sprite: _CD/Clothing/GarmenPacks/debugpack.rsi
👍

2024-01-13 03:30 UTC, KittenColony commented
> We could set this up to have cosmetic items for department heads, I would want some discussion before we went and did that though. (Such as if its even needed)

this is just a framework atm so that we _can_ do this sort of thing

2024-01-13 17:26 UTC, LankLTE approved these changes

2024-01-13 17:27 UTC, merged