Make SOP guidebook entry acutally good.
cosmatic-drift-14/cosmatic-drift pull request #326
Opened 2024-07-13 14:52 UTC by dffdff2423

## About the PR

Title

## Why / Balance

A few changes that I did not have time to make before the other PR was merged.

## Technical details

restricted.xml is now fully generated by tablegen.nu

2024-07-13 20:28 UTC, Nairodian requested changes

2024-07-13 20:28 UTC, Nairodian commented on Resources/ServerInfo/Guidebook/_CD/sop/restricted.tbl
> +\[[color=#f39f27]Engineering[color]\]|Enginnering goggles||
"_Enginnering_ goggles"

2024-07-14 17:54 UTC, Nairodian approved these changes
I'm not going to hold the PR back for it, but one last thing since you have an SOP PR open already, are you able to make it so rule 3.7 lists our own SOP instead of Wizard's Den?

2024-07-15 06:48 UTC, LankLTE approved these changes
thanks

2024-07-15 06:49 UTC, merged