Re-add atmos remote + CE remote changes
cosmatic-drift-14/cosmatic-drift pull request #368
Opened 2024-08-18 04:21 UTC by Mangohydra

## About the _(𝓶𝓪𝓵𝓭 )_ PR
I've re-added the atmos fire remote because i've seen no cases of abusing it here. that pr makes more sense on upstream, not here.
I also gave the CE's remote firelock access to match it, because it sounds a bit dumb to not give it to the CE as well.
## Why / Balance
days since last fire related incident: 0
Jokes aside, gas leak events (trit and plasma specifically) have become at least 10 times more scary with the removal of fire remotes because you can't prevent that one guy from just wandering in with no situational awareness at all with a lit cigar. 
(and everyone forces the firelocks open anyways)

## Media
the remote
![image](https://github.com/user-attachments/assets/61d1e49a-5243-4b9f-bda6-b81f3352ca46)
bolted firelocks!! yippee!!!!
![image](https://github.com/user-attachments/assets/3b58191d-f918-4562-9270-dd9ada32dbbb)

## Requirements
- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame 

**Changelog**
:cl:
- The fire fighting remote (atmos remote) is back! YIPPEE!!!!!
- The CE can now bolt firelocks

2024-08-18 04:25 UTC, LankLTE commented
I mean like you can just weld the doors shut, but also if this is going to be re-added it should be within the _CD namespace

2024-08-18 04:26 UTC, Ariphylor commented
I approve of this message

2024-08-18 04:28 UTC, Mangohydra commented
> I mean like you can just weld the doors shut, but also if this is going to be re-added it should be within the _CD namespace

i don't know how to do that, let me know where i need to add that and i'll fix it

2024-08-18 04:30 UTC, Mangohydra commented
> Move all your files into a _CD folder. For example instead of /Prototypes/Entities, it would instead be /Protoypes/_CD/Entities. Most of the folders should already exist.

got it, working on it now

2024-08-18 04:41 UTC, Mangohydra commented
@PursuitInAshes just the remote entity or _everything_ i changed?

2024-08-18 05:45 UTC, Mangohydra commented
I believe I got everything marked up or moved, yippee!!

2024-08-18 05:57 UTC, Mangohydra commented on Resources/Changelog/Changelog.yml
changed it back, its pristine now, hopefully.

2024-08-18 21:33 UTC, dffdff2423 reviewed
Technical side looks fine to me.

However, I am a bit mixed on bolting firelocks because I don't think there is a way to un-bolt them without a remote (please correct me if I am forgetting something).

2024-08-18 21:34 UTC, dffdff2423 commented on Resources/Changelog/Changelog.yml
This file is supposed to be generated automatically but we don't have that set up.

2024-08-19 02:52 UTC, Mangohydra commented
> Technical side looks fine to me.
> 
> However, I am a bit mixed on bolting firelocks because I don't think there is a way to un-bolt them without a remote (please correct me if I am forgetting something).

I'm pretty sure you can unbolt them like a normal door with a screwdriver and multitool/wirecutters

2024-08-19 03:11 UTC, dffdff2423 commented
Just tested it and I was not able to hack it open after it was bolted.

2024-08-19 04:04 UTC, Mangohydra commented
> Just tested it and I was not able to hack it open after it was bolted.

Checked it just to be sure, yeah they can't be hacked, could've sworn they could have been before.
maybe i might make a PR for that next, who knows (i won't)

2024-08-19 21:47 UTC, dffdff2423 commented
In that case can you remove the ability to bolt firelocks with this remote?

2024-08-21 21:23 UTC, deepdarkdepths commented
> I mean like you can just weld the doors shut, but also if this is going to be re-added it should be within the _CD namespace

>You can just weld the doors shut
If I am in a situation where I _need_ to have firelocks locked down, which will likely be a tritium or plasma leak most of the time, I'd rather not add to the fire or light the existing plasma aflame. The door remote makes this problem null entirely.

2024-08-21 21:30 UTC, dffdff2423 commented
> I'd rather not add to the fire or light the existing plasma aflame. The door remote makes this problem null entirely.

You can always bolt the door by hacking it.

2024-08-31 00:21 UTC, dffdff2423 requested changes
We are alright with merging this if you add the ability to hack firelocks.

2024-11-16 02:47 UTC, LankLTE commented
I’m going to close this as it seems like it’s not desired and has been idle. If you’d like it reopened, please comment / let me know.

2024-11-16 02:54 UTC, closed without merging