Add new lobby screen by Zephyr
cosmatic-drift-14/cosmatic-drift pull request #418
Opened 2024-09-19 23:19 UTC by dffdff2423

## About the PR

Title

## Breaking changes

I removed all of the widen title screens. Let me know if you want me to revert this

2024-09-21 05:42 UTC, LankLTE commented
I'd rather not restrict us to one lobby art.

2024-09-21 16:17 UTC, dffdff2423 commented
I fucked my branch again.... one second

2024-09-23 17:14 UTC, LankLTE requested changes

2024-09-23 17:14 UTC, LankLTE commented on Resources/Prototypes/_CD/lobbyscreens.yml
> +  id: TheDirft
TheDirft

2024-09-24 16:39 UTC, merged