Contraband Drop 1 - Narcotics 1
cosmatic-drift-14/cosmatic-drift pull request #466
Opened 2024-11-13 06:03 UTC by KittenColony

A new collection of PRs. _Contraband._
## About the PR
Adds several new items and sources for narcotics, including brand new ones with Unique* effects!

## Why / Balance
Characters might have a background with substance abuse, currently, the only real way to get these is through chemistry, spaceshrooms, maintpills or the occasional admin-run dealer events. This PR adds new sources for people to get their fixes, while also giving Security something to track down and interact with.

## Technical details
Primarily YAML code, does include 1 new reagent, reaction and FTL files, vending machine changes not name-spaced, are tagged with [# _CD]

## Media
:todo:

## Requirements

- [x] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:todo:

2024-11-13 06:04 UTC, KittenColony commented
PR made to find issue with Dynamoxine using tests

2024-11-13 06:33 UTC, DrSmugleaf requested changes
Welds asked me for a PR review in voice chat

2024-11-13 06:33 UTC, DrSmugleaf commented on Resources/Prototypes/_CD/Reagents/narcotics.yml
> +          min: 1
You are missing an indentation here, it is reading this as part of the conditions, not as part of the reagent threshold
```suggestion
            reagent: Epinephrine # DO NOT USE A FUCKING EPEN
            min: 1
```

2024-11-13 07:17 UTC, KittenColony commented
motherfucking GOD, HOW?

2024-11-14 06:59 UTC, KittenColony commented
I would like to apologise in advance to you, Aquif.

2024-11-14 11:03 UTC, KittenColony commented
GOD FUCKING HELP ME I HATE CRAFTING CODE

2024-11-14 12:42 UTC, KittenColony commented
fucking what

2024-11-14 15:36 UTC, MilonPL requested changes
you need to have a step at the `empty` node, i used the screwdriver but whatever, you got it from here I hope

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Recipes/Crafting/Graphs/narcotics.yml
> +    entity: wrappedBakepackage
```suggestion
- type: constructionGraph
  id: WrappedBakePackage
  start: start
  graph:
  - node: start
    edges:
    - to: empty
      steps:
      - tag: EmptyPacket
        name: an empty packet
        doAfter: 1
  - node: empty
    entity: EmptyPacket
    edges:
    - to: bakeWrapped
      steps:
      - tool: Screwing
        doAfter: 1
      conditions:
      - !type:MinSolution
        solution: drink
        reagent:
          ReagentId: Bake
        quantity: 30
  - node: bakeWrapped
    entity: WrappedBakePackage

```

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Recipes/Crafting/Graphs/package.yml
> +    - to: emptypacket
`emptyPacket` instead

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Recipes/Crafting/Graphs/package.yml
> +  id: foldsmugglerpackage
`FoldSmugglerPackage`

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Recipes/Crafting/Graphs/package.yml
> +  - node: emptypacket
above

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Misc/contraband.yml
`EmptyPacket` should have a way for you to add the solution that doesn't involve the addreagent command xP

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Hydroponics/leaves.yml
> +
only one linebreak here

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Reagents/narcotics.yml
> +
doesn't need so many newlines

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Reagents/narcotics.yml
> +
above

2024-11-14 15:36 UTC, MilonPL commented on Resources/Prototypes/_CD/Reagents/narcotics.yml
> +        amount: 0.8
EOF newline

2024-11-15 01:42 UTC, KittenColony commented
1.0 is marked as complete and ready for review.

2024-11-15 12:28 UTC, MilonPL requested changes
`type` > `abstract` > `parent` > `id` > `name` > `suffix` > `description` > `components`
yaml conventions everywhere jfc

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  suffix: weh
why does this need the suffix

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +    - CigPackUnmarkedEquili
use entitytables

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Misc/contraband.yml
> +    node: bakeWrapped
EOF newline

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  components:
above

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  components:
.

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  suffix: happsiness
happsiness

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  suffix: happsiness
pro

2024-11-15 12:28 UTC, MilonPL commented on Resources/Prototypes/_CD/Recipes/Crafting/narcotics.yml
> +  name: fold smuggling packet
`folded` not `fold` or otherwise you will get `to create fold smuggling packet...`

2024-11-16 01:26 UTC, KittenColony commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/cigarette.yml
> +  suffix: happsiness
intentional
happiness + Psicodine

2024-11-16 01:30 UTC, KittenColony commented on Resources/Prototypes/_CD/Entities/Objects/Consumable/Smokeables/Cigarettes/packs.yml
> +  suffix: weh
clinging to uniformity

2024-11-18 03:34 UTC, dffdff2423 commented
It looks like you marked the above review from Milon as resolved but I don't see the actual changes. Did you forget to push them?

2024-11-18 03:40 UTC, KittenColony commented
I'm not going to rewrite every YAML entity for the sake of convention when the vast majority of the existing code doesn't follow it

it was a pain in the ass to even get the random pack vending to work at all, and what's already there was copied from how the random jumpsuits are dispensed

HapPsiness is intentional

2024-11-19 22:43 UTC, LankLTE commented
Test fail is related I believe

2024-11-19 22:44 UTC, KittenColony commented
![image](https://github.com/user-attachments/assets/4b4a4b7e-1970-4553-a171-9a519bdddd5d)

2024-11-19 22:53 UTC, dffdff2423 reviewed
We should be moving in the direction of following the conventions, even if old code does not. Having a random order for entity members for each entity damages readability because it requires more effort to see if an entity has a given member. `entityTable`s are preferred because they allow more configuration on how random values are chosen.

We are currently discussing the mechanics of the reagents privately. I will get back to you shortly on those.

2024-11-19 22:54 UTC, dffdff2423 commented
I reran the test just in-case (although it looks like Lank did already).

2024-11-20 23:24 UTC, KittenColony commented
as an aside with the reagents, all of them barring the sap and tea should be considered restricted chemicals / as non-insignificant contraband by the crew / security

2024-11-24 05:00 UTC, dffdff2423 commented
Currently blocked awaiting private maintainer discussion. I will update you as soon as possible.

2024-12-01 04:51 UTC, KittenColony commented
Are you fucking kidding me

2024-12-04 20:20 UTC, Nairodian approved these changes
Okay I think this is alright. Next time you make a PR that adds/changes a lot I ask that you be more descriptive in your description about what the items actually functionally do instead of just a vague overview.

2024-12-04 21:14 UTC, dffdff2423 commented
Next time you make a pull request please break it up into multiple smaller PRs so it does not take a month to review. I don't care if you spam the repo with 20 PRs. It is far easier to review because I don't need to set aside an hour and I can consider each thing in isolation rather than all at once.

2024-12-26 18:44 UTC, LankLTE commented on Resources/Prototypes/_CD/Entities/Objects/Misc/contraband.yml
> +    price: 10000 # worth the risk?
Just remember to lower this if it ends up causing problems.

2024-12-28 00:17 UTC, LankLTE commented
Will merge this after the upstream merge.

2024-12-28 06:46 UTC, merged