ports membral wings from Sector Umbra
cosmatic-drift-14/cosmatic-drift pull request #471
Opened 2024-11-16 23:39 UTC by lunarcomets

* moff

moff membral

* fix the thing

---------

## About the PR

just ports the Membral Wings marking from Sector Umbra to CD, courtesy of @Sadie-silly 

## Why / Balance

bee
## Media

![image](https://github.com/user-attachments/assets/a09c9cec-d72e-4514-b268-bffd08da95db)
![image](https://github.com/user-attachments/assets/99327c2b-f5cb-4c53-9772-fe7580ea50d3)
![image](https://github.com/user-attachments/assets/58ab5309-b6b8-4b3b-a943-22d8a08d2dae)
![image](https://github.com/user-attachments/assets/3234c89f-ddc5-4be3-a5f9-d9fde8b256cc)

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

ported membral wings! buzz buzz!

2024-11-16 23:45 UTC, dffdff2423 requested changes
Looks fine, just needs to be in the CD namespace to reduce merge conflicts.

2024-11-16 23:45 UTC, dffdff2423 commented on Resources/Locale/en-US/markings/moth.ftl
> +
Needs to be in the _CD namespace

2024-11-16 23:45 UTC, dffdff2423 commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/moth.yml
> +- type: marking
Random space

2024-11-16 23:45 UTC, dffdff2423 commented on Resources/Prototypes/Entities/Mobs/Customization/Markings/moth.yml
> +
Needs to be in the CD namespace

2024-11-16 23:45 UTC, dffdff2423 commented on Resources/Textures/Mobs/Customization/Moth/moth_wings.rsi/meta.json
> +        "directions": 4
Instead of modifying upstream's RSI, you should create a new RSI in the _CD directory.

2024-11-16 23:59 UTC, lunarcomets commented
was pulled from a fork without dedicated namespaces but this maybe fixes it? i'll have to see later, heading to work now

2024-11-17 00:31 UTC, Sadie-silly commented
i am sadie-silly and i approve this message

2024-11-17 01:31 UTC, PursuitInAshes commented on Resources/Textures/_CD/Mobs/Customization/Moth/moth_wings.rsi/meta.json
Just want to point this out, is this copyright accurate?

2024-11-17 02:21 UTC, lunarcomets commented on Resources/Textures/_CD/Mobs/Customization/Moth/moth_wings.rsi/meta.json
it isn't, only because i didn't have time to fix it before having to leave it, i'll fix it in here and the origin fork when i can in a little while

2024-11-17 02:35 UTC, PursuitInAshes commented on Resources/Textures/_CD/Mobs/Customization/Moth/moth_wings.rsi/meta.json
Alright, thanks. Just wanted to drop a comment to make sure.

2024-11-17 02:46 UTC, lunarcomets commented on Resources/Textures/_CD/Mobs/Customization/Moth/moth_wings.rsi/meta.json
course, i'll resolve this review too when it's done, thanks for the reminder!

2024-11-17 04:15 UTC, dffdff2423 commented
This has my approval as soon as the copyright issue is sorted out.

2024-11-17 06:31 UTC, lunarcomets commented on Resources/Textures/_CD/Mobs/Customization/Moth/moth_wings.rsi/meta.json
resolved with most recent commit

2024-11-17 15:46 UTC, dffdff2423 approved these changes

2024-11-18 00:29 UTC, LankLTE commented
I'll want this moved to subspecies once those exist but for now it's fine.

2024-11-18 00:29 UTC, merged