job slots console
cosmatic-drift-14/cosmatic-drift pull request #476
Opened 2024-11-19 20:20 UTC by MilonPL

## About the PR

adds a job slots console that does exactly what it says
admins get a fancy version that can also make slots infinite or not

## Why / Balance

https://github.com/cosmatic-drift-14/cosmatic-drift/issues/346

## Technical details

new ui, system, component, etc etc
has a ProtoId hashset to blacklist specific jobs from being modified
Debug bool for the admins, can probably implement more functionality in the future with it

## Media

<details><summary>Click me!</summary>
<br>
Boo!

![image](https://github.com/user-attachments/assets/edf564b6-dd9f-4d96-901d-d1bd7448f60e)

admin version:
![image](https://github.com/user-attachments/assets/df9cc2e1-7733-4c8f-ab1f-bec476a590df)

sprites:
![image](https://github.com/user-attachments/assets/fffbccbd-a3d2-4bc3-8412-5d0e41e6e1e0)

blacklist tooltip:
![image](https://github.com/user-attachments/assets/1aa6bc0c-fca7-4e72-9daa-bebf820adc3b)

2024-11-19 22:36 UTC, dffdff2423 requested changes

2024-11-19 22:50 UTC, MilonPL commented on Content.Server/_CD/JobSlotsConsole/JobSlotsConsoleSystem.cs
> +        // This is a mess but it was the only way to update the UI when job slots change
doesn't handle events (if they did ever happen), toolshed commands, or any other means of changing job slots
this shouldn't really be that resource intensive

2024-11-19 22:52 UTC, MilonPL commented on Content.Server/_CD/JobSlotsConsole/JobSlotsConsoleSystem.cs
> +            if (message.SetInfinite.Value)
line 95 checks if it's not null, then line 97 checks if it's true or false since it's a nullable bool

2024-11-19 22:54 UTC, MilonPL commented on Content.Client/_CD/JobSlotsConsole/JobRow.xaml.cs
> +    public JobRow(string jobId, int? slots, bool blacklisted)
yes real

2024-11-19 22:54 UTC, dffdff2423 commented on Content.Server/_CD/JobSlotsConsole/JobSlotsConsoleSystem.cs
> +            if (message.SetInfinite.Value)
Oh right.

2024-11-19 22:55 UTC, dffdff2423 commented on Content.Server/_CD/JobSlotsConsole/JobSlotsConsoleSystem.cs
> +        // This is a mess but it was the only way to update the UI when job slots change
Fair point. It is only 20 or so things.

2024-11-20 00:01 UTC, dffdff2423 approved these changes

2024-11-27 02:12 UTC, LankLTE commented
Kinda meh on this, I think letting heads block more people from joining their department is generally gonna be a net negative. Blocking heads specifically makes sense given promotions but the only way to allow that currently is to blacklist everything.

2024-11-28 16:27 UTC, Nairodian commented
> Kinda meh on this, I think letting heads block more people from joining their department is generally gonna be a net negative. Blocking heads specifically makes sense given promotions but the only way to allow that currently is to blacklist everything.

I kind of disagree, because it's HoP locked anyways, individual heads aren't going to be able to use this console meaning they'd have to go up and ask the HoP to restrict their whole department which is for sure going to give them a momentary odd look. I say we try it out with all the jobs being accessible (except Captain+) and then from there fine tune it if it goes poorly.

2024-11-28 17:32 UTC, LankLTE commented
> I kind of disagree, because it's HoP locked anyways, individual heads aren't going to be able to use this console meaning they'd have to go up and ask the HoP to restrict their whole department which is for sure going to net them a momentary odd look. I say we try it out with all the jobs being accessible (except Captain+) and then from there fine tune it if it goes poorly.

Alright, next question then is if this needs to be a separate console that we have to map instead of being on a different console (probably the ID one).

2024-12-01 22:07 UTC, dffdff2423 commented
> Alright, next question then is if this needs to be a separate console that we have to map instead of being on a different console (probably the ID one).

I think it should be a separate console. I think it would be a bit strange to put 2 UIs on the same entity.

2024-12-02 04:46 UTC, LankLTE commented
> I think it should be a separate console. I think it would be a bit strange to put 2 UIs on the same entity.

Alright I've been convinced you can hit merge whenever.

2024-12-14 02:16 UTC, merged

2025-01-29 23:56 UTC, metalgearsloth commented on Content.Client/_CD/JobSlotsConsole/JobSlotsConsoleBUI.cs
> +
Use SendPredictedMessage and make the whole thing predicted?

2025-01-29 23:56 UTC, metalgearsloth commented on Content.Client/_CD/JobSlotsConsole/JobSlotsConsoleBUI.cs
> +    }
this.CreateWindow?

2025-01-29 23:56 UTC, metalgearsloth commented on Content.Client/_CD/JobSlotsConsole/JobSlotsConsoleBUI.cs
> +    }
Obsolete

2025-01-29 23:56 UTC, metalgearsloth commented on Content.Client/_CD/JobSlotsConsole/JobSlotsConsoleMenu.xaml.cs
> +}
This should really be on jobs or something rather than here.